ProyectoFDI.v2/Controllers/ClubController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoFDI.v2.Code;
using ProyectoFDI.v2.Models;

namespace ProyectoFDI.v2.Controllers
{
    public class ClubController : Controller
    {
        private string apiUrl;

        public ClubController(IConfiguration configuration)
        {
            apiUrl = configuration["urlBase"].ToString() + "Club/";
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // GET: ClubController
        public ActionResult Index()
        {
            var data = APIConsumer<Club>.Select(apiUrl);
            return View(data);
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // GET: ClubController/Details/5
        public ActionResult Details(int id)
        {
            var data = APIConsumer<Club>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // GET: ClubController/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // POST: ClubController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Club club)
        {
            try
            {
                APIConsumer<Club>.Insert(apiUrl, club);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(club);
            }
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // GET: ClubController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = APIConsumer<Club>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // POST: ClubController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Club club)
        {
            try
            {
                APIConsumer<Club>.Update(apiUrl + id.ToString(), club);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(club);
            }
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // GET: ClubController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = APIConsumer<Club>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Entrenador")]
        // POST: ClubController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Club club)
        {
            try
            {
                APIConsumer<Club>.Delete(apiUrl + id.ToString());
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(club);
            }
        }
    }
}

ProyectoFDI.v2/Controllers/SedeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ProyectoFDI.v2.Code;
using ProyectoFDI.v2.Models;

namespace ProyectoFDI.v2.Controllers
{
    public class SedeController : Controller
    {
        private string apiUrl;

        public SedeController(IConfiguration configuration)
        {
            apiUrl = configuration["urlBase"].ToString() + "Sede/";
        }

        [Authorize(Roles = "Administrador,Juez")]
        // GET: SedeController
        public ActionResult Index()
        {
            var data = APIConsumer<Sede>.Select(apiUrl);
            return View(data);
        }

        [Authorize(Roles = "Administrador,Juez")]
        // GET: SedeController/Details/5
        public ActionResult Details(int id)
        {
            var data = APIConsumer<Sede>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Juez")]
        // GET: SedeController/Create
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Administrador,Juez")]
        // POST: SedeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sede sede)
        {
            try
            {
                APIConsumer<Sede>.Insert(apiUrl, sede);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(sede);
            }
        }

        [Authorize(Roles = "Administrador,Juez")]
        // GET: SedeController/Edit/5
        public ActionResult Edit(int id)
        {
            var data = APIConsumer<Sede>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Juez")]
        // POST: SedeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Sede sede)
        {
            try
            {
                APIConsumer<Sede>.Update(apiUrl + id.ToString(), sede);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(sede);
            }
        }

        [Authorize(Roles = "Administrador,Juez")]
        // GET: SedeController/Delete/5
        public ActionResult Delete(int id)
        {
            var data = APIConsumer<Sede>.SelectOne(apiUrl + id.ToString());
            return View(data);
        }

        [Authorize(Roles = "Administrador,Juez")]
        // POST: SedeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Sede sede)
        {
            try
            {
                APIConsumer<Sede>.Delete(apiUrl + id.ToString());
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View(sede);
            }
        }
    }
}

ProyectoFDI.v2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProyectoFDI.v2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProyectoFDI.v2.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lib/limonte-sweetalert2/sweetalert2.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.min.css" />

    <link rel="stylesheet" href="https://cdn.datatables.net/1.12.1/css/dataTables.bootstrap5.min.css" />
@*    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" />*@
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    <style type="text/css">

        .navbar .nav-item:not(:last-child) {
            margin-right: 35px;
        }

        .dropdown-toggle::after {
            transition: transform 0.15s linear;
        }

        .show.dropdown .dropdown-toggle::after {
            transform: translateY(3px);
        }

        .dropdown-menu {
            margin-top: 0;
        }

        .nav-item {
            list-style: none;
        }

        .navbar-nav li a {
            text-decoration: none;
        }

        .navbar-nav li ul {
            display: none;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProyectoFDI.v2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class=" collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Catálogos</a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown1">
                                <a class="dropdown-item" asp-area="" asp-controller="Deportista" asp-action="Index">Deportistas</a>
                                @if (User.IsInRole("Administrador"))
                                {
                                    <a class="dropdown-item" asp-area="" asp-controller="Entrenador" asp-action="Index">Entrenadores</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Juez" asp-action="Index">Jueces</a>
                                }
                                <a class="dropdown-item" asp-area="" asp-controller="Competencia" asp-action="Index">Listado de Competencias</a>
                            </div>
                        </li>
                        @if (User.IsInRole("Administrador") || User.IsInRole("Juez")){
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Competencias</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown2">
                                    <a class="dropdown-item" asp-area="" asp-controller="Competencia" asp-action="Create">Crear Competencias</a>                                    
                                    <a class="dropdown-item" asp-area="" asp-controller="Competencia" asp-action="Resultados">Agregar Resultados</a>
                                </div>
                            </li>
                        }
                        
                        @if (User.IsInRole("Administrador") || User.IsInRole("Entrenador") || User.IsInRole("Juez"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Entidades</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown3">
                                    @if (User.IsInRole("Administrador") || User.IsInRole("Juez"))
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="Sede" asp-action="Index">Sedes</a>
                                    }
                                    @if (User.IsInRole("Administrador") || User.IsInRole("Entrenador"))
                                    {
                                        <a class="dropdown-item" asp-area="" asp-controller="Club" asp-action="Index">Clubes</a>
                                    }
                                </div>
                            </li>
                        }
                        @if (User.IsInRole("Administrador"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="" id="navbarDropdown4" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Administración</a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown4">
                                    <a class="dropdown-item" asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a>   
                                </div>
                            </li>
                        }

                        @* Home
                        Catalogo : Deportistas - Entrenadores - Jueces  - Listado Competencias
                        Competencias : Crear Competencia - Agregar Resultados
                        Entidades : Sedes - Clubes
                        Administración: Usuarios
                        *@

                        @*<li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@
                    </ul>
                </div>
                <button class="alert-danger">
                    <a class="nav-link text-dark" asp-area="" asp-controller="Acceso" asp-action="Salir">Cerrar Sesión</a>
                </button>
            </div>
        </nav>
    </header>
    <div class="container">
        <script src="~/lib/limonte-sweetalert2/sweetalert2.min.js" asp-append-version="true"></script>
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_NotificationPartial" />
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - ProyectoFDI.v2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script>
        const $dropdown = $(".dropdown");
        const $dropdownToggle = $(".dropdown-toggle");
        const $dropdownMenu = $(".dropdown-menu");
        const showClass = "show";
        $(window).on("load resize", function () {
            if (this.matchMedia("(min-width: 768px)").matches) {
                $dropdown.hover(
                    function () {
                        const $this = $(this);
                        $this.addClass(showClass);
                        $this.find($dropdownToggle).attr("aria-expanded", "true");
                        $this.find($dropdownMenu).addClass(showClass);
                    },
                    function () {
                        const $this = $(this);
                        $this.removeClass(showClass);
                        $this.find($dropdownToggle).attr("aria-expanded", "false");
                        $this.find($dropdownMenu).removeClass(showClass);
                    }
                );
            } else {
                $dropdown.off("mouseenter mouseleave");
            }
        });
    </script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

ProyectoFDI.v2/Views/Shared/_NotificationPartial.cshtml
<script>@if (TempData["notification"] != null)
        @Html.Raw(TempData["notification"].ToString())
    ;</script>